### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by WuZhiMing2** [NOHNOLIFE/mangaview#1]
打开根目录下的index.html报错，页面空白并且控制台报错
Access to script at 'file:///F:/src/main.ts' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, isolated-app, chrome-extension, chrome, https, chrome-untrusted.
如果要把目录下的所有文件移动到磁盘下，此设计我觉得是不合理的

**Comment by NOHNOLIFE** [comment]
> 打开根目录下的index.html报错，页面空白并且控制台报错 Access to script at 'file:///F:/src/main.ts' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, isolated-app, chrome-extension, chrome, https, chrome-untrusted. 如果要把目录下的所有文件移动到磁盘下，此设计我觉得是不合理的

这是PWA网页应用，不需要下载代码库内的任何东西
直接浏览器访问该网址即可：https://nohnolife.github.io/mangaview/dist/index.html
中文指南：https://github.com/NOHNOLIFE/mangaview/blob/main/README.zh-CN.md
