### ISSUE TITLE
图片的顺序是混乱的

### ISSUE THREAD

**Issue by QihangYang** [NOHNOLIFE/mangaview#2]

**Comment by NOHNOLIFE** [comment]
如果你是载入的文件夹，则按照文件夹内每个文件的名称进行排序。
如果你是载入的多个图片文件，则会按照当前资源管理器界面内的排序顺序以及拖拽文件时的【鼠标悬停位置指向的文件为首】进行展示
也就是说进行拖拽操作的时候，先选中了多个文件，然后用鼠标按住第一个文件进行拖放操作就能和当前资源管理器内的排序一致

**Comment by QihangYang** [comment]
你好！我发现如果文件夹里并不全是图片文件，比如混杂了一个txt文件，那么使用open folder打开就不是按照图片名称的顺序进行排列的。如果全是图片文件则不存在这个问题。这可能是个bug。

**Comment by NOHNOLIFE** [comment]
> 你好！我发现如果文件夹里并不全是图片文件，比如混杂了一个txt文件，那么使用open folder打开就不是按照图片名称的顺序进行排列的。如果全是图片文件则不存在这个问题。这可能是个bug。

你先更新一下 Ctrl+Shift+R ，再试试看看还有错吗

**Comment by QihangYang** [comment]
> > 你好！我发现如果文件夹里并不全是图片文件，比如混杂了一个txt文件，那么使用open folder打开就不是按照图片名称的顺序进行排列的。如果全是图片文件则不存在这个问题。这可能是个bug。
> 
> 你先更新一下 Ctrl+Shift+R ，再试试看看还有错吗

我从github重新打开的页面，还是存在同样的问题。

**Comment by QihangYang** [comment]
举个例子吧，我使用的是macOS，这是我的某一个文件夹。使用open folder打开之后图片就是完全乱序的。如果全选然后鼠标拖进去的话顺序就是正常的。
.
├── pageInfo.txt
├── pic_002.png
├── pic_003.png
├── pic_004.png
├── pic_005.png
├── pic_006.png
├── pic_007.png
├── pic_008.png
├── pic_009.png
└── pic_010.png

**Comment by NOHNOLIFE** [comment]
> 举个例子吧，我使用的是macOS，这是我的某一个文件夹。使用open folder打开之后图片就是完全乱序的。如果全选然后鼠标拖进去的话顺序就是正常的。 . ├── pageInfo.txt ├── pic_002.png ├── pic_003.png ├── pic_004.png ├── pic_005.png ├── pic_006.png ├── pic_007.png ├── pic_008.png ├── pic_009.png └── pic_010.png

因为我没有macOS设备，如果是你描述的这种情况的话，我也没办法进行debug。所以只能建议你一律使用拖拽文件夹的方式来打开文件

**Comment by QihangYang** [comment]
ok...谢谢！
