### ISSUE TITLE
能增加中文语言嘛？我是指书库那些地方。

### ISSUE THREAD

**Issue by MarkAceNew** [NOHNOLIFE/mangaview#3]
增加中文语言。

**Comment by NOHNOLIFE** [comment]
> 增加中文语言。

如果你说的是书籍标题：书籍目录是按照文件夹目录的名称显示的，需要文件夹是中文名称软件上才会显示中文
如果你说的是已汉化的书籍过滤：在标题关键字搜索框内分别搜索： 中国 、化、chinese 。 或者在源管理器内用上述关键字搜索，把已汉化的书籍单独放到一个文件夹内，然后只把汉化过的书籍放入阅读器

**Comment by MarkAceNew** [comment]
> > 增加中文语言。
> 
> 如果你说的是书籍标题：书籍目录是按照文件夹目录的名称显示的，需要文件夹是中文名称软件上才会显示中文 如果你说的是已汉化的书籍过滤：在标题关键字搜索框内分别搜索： 中国 、化、chinese 。 或者在源管理器内用上述关键字搜索，把已汉化的书籍单独放到一个文件夹内，然后只把汉化过的书籍放入阅读器

我说是“My Book”这样的显示页面字符，倒不是看不懂，单纯强迫症，改中文好看些，而且中间的提示拖拽文件的提示三语也显得不美观，我本来想自己改，发现不会在本地搭。遂放弃。

**Comment by NOHNOLIFE** [comment]
> > > 增加中文语言。
> > 
> > 
> > 如果你说的是书籍标题：书籍目录是按照文件夹目录的名称显示的，需要文件夹是中文名称软件上才会显示中文 如果你说的是已汉化的书籍过滤：在标题关键字搜索框内分别搜索： 中国 、化、chinese 。 或者在源管理器内用上述关键字搜索，把已汉化的书籍单独放到一个文件夹内，然后只把汉化过的书籍放入阅读器
> 
> 我说是“My Book”这样的显示页面字符，倒不是看不懂，单纯强迫症，改中文好看些，而且中间的提示拖拽文件的提示三语也显得不美观，我本来想自己改，发现不会在本地搭。遂放弃。

因为暂时没做多语言国际化，所以界面上以最为通用的英文为主。
或者你可以试试使用谷歌浏览器右键菜单里自带的“翻译成中文”
