### ISSUE TITLE
文件名排序部分代码有bug

### ISSUE THREAD

**Issue by QihangYang** [NOHNOLIFE/mangaview#4]
App.vue中第30行，文件名排序部分`return x - y`。如果文件名中存在不含数字的文件（比如cover.png），两个字符串进行减法操作结果会是NaN，文件排序会乱掉。

**Comment by NOHNOLIFE** [comment]
已修改，请清空缓存刷新重载

**Comment by QihangYang** [comment]
这样改好像不太对吧，反而更乱了。是不是应该全部转化成字符串，然后用字符串排序会更好一些？比如localeCompare？

**Comment by NOHNOLIFE** [comment]
> 这样改好像不太对吧，反而更乱了。是不是应该全部转化成字符串，然后用字符串排序会更好一些？比如localeCompare？

一般按照数字排序，这样做是为了让诸如1.png  2.png 3.png 4.png …… 22.png ……34.png……这种没加占位符的数字能够正常排序。

按照字符串A-Z排序的话，一般不会有这样命名漫画文件的做法。所以这里只排序数字，非数字字符串则不对其排序。

**Comment by QihangYang** [comment]
好的，明白了。感谢！

**Comment by QihangYang** [comment]
大佬，新版本的排序错的更离谱了，就是算1.png 2.png 3.png的顺序也是不对的，你可以测试一下。

**Comment by NOHNOLIFE** [comment]
> 大佬，新版本的排序错的更离谱了，就是算1.png 2.png 3.png的顺序也是不对的，你可以测试一下。

改好了
